import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { expect, it } from 'vitest'

const chat = readFileSync(join(import.meta.dirname, '../../app/pages/bots/[id].vue'), 'utf8')

function block(start: string, end: string): string {
  const from = chat.indexOf(start)
  const to = chat.indexOf(end, from + start.length)
  expect(from).toBeGreaterThan(-1)
  expect(to).toBeGreaterThan(from)
  return chat.slice(from, to)
}

it('overlays a slim composer on one scrolling Chat pane', () => {
  const composer = block('.composer {', '.composer-row,')
  const row = block('.composer-row {', '.composer-row.multiline')
  const thread = block('.thread {', '.bubble {')

  expect(composer).toContain('position: absolute')
  expect(composer).toContain('pointer-events: none')
  expect(composer).toContain('env(safe-area-inset-bottom')
  expect(composer).toContain('var(--bg-chat) calc(var(--composer-gap) + 2px)')
  expect(composer).toContain('--composer-gap')
  expect(composer).not.toContain('background: transparent')
  expect(composer).not.toContain('background: var(--composer)')
  const foot = block('.composer-foot {', '.composer-foot::before')
  const band = block('.composer-foot::before {', '.composer-row,')
  expect(foot).not.toContain('background:')
  expect(band).toContain('top: 50%')
  expect(band).toContain('bottom: -2px')
  expect(band).toContain('background: var(--bg-chat)')
  expect(band).not.toContain('border-radius')
  expect(row).toContain('background: var(--composer)')
  expect(row).toContain('--composer-pad: 0.3rem;')
  expect(row).toContain('padding: var(--composer-pad);')
  expect(row).toContain('--composer-inner-radius: calc(var(--composer-button) / 2);')
  expect(row).toContain('flex-direction: column')
  const tall = block('.composer-row.multiline {', '.composer-line {')
  expect(tall).toContain('calc(var(--composer-inner-radius) + var(--composer-pad) + var(--composer-rim))')
  const line = block('.composer-line {', '.composer-row.multiline .composer-line')
  expect(line).toContain('align-items: center')
  const trayAt = chat.indexOf('class="pending-chips"')
  expect(trayAt).toBeGreaterThan(chat.indexOf('class="composer-row"'))
  expect(trayAt).toBeLessThan(chat.indexOf('class="composer-line"'))
  expect(chat).toContain(`:placeholder="pendingAttachments.length > 0
                    ? 'Добавьте сообщение или просто отправьте'`)
  expect(row).not.toContain('safe-area')
  expect(thread).toContain('var(--composer-clearance)')
  expect(thread).toContain('var(--thread-end-gap)')
  expect(thread).toContain('overflow: auto')
  expect(thread).toContain('overflow-anchor: none')
  expect(chat).toContain('--thread-end-gap: 5rem')
  expect(chat).toContain('el.scrollTop = el.scrollHeight')
  expect(chat).toContain('flush: \'post\', immediate: true')

  const formEnd = chat.indexOf('</form>')
  const jump = chat.indexOf('class="to-latest"')
  expect(formEnd).toBeGreaterThan(-1)
  expect(jump).toBeGreaterThan(formEnd)
  expect(chat).toContain('aria-label="Scroll to latest"')
  expect(chat).toContain('behavior: reduce ? \'auto\' : \'smooth\'')

  const control = block('.to-latest {', '.to-latest svg')
  expect(control).toContain('left: 50%')
  expect(control).toContain('translateX(-50%)')
  expect(control).toContain('var(--composer-clearance)')
  expect(control).toContain('border-radius: 999px')
  expect(control).toContain('background: var(--composer)')
})

it('overlays a Chat pill and pads the thread above it', () => {
  const thread = block('.thread {', '.bubble {')
  const pill = block('.identity {', '.identity:hover')
  expect(chat).not.toContain('<header')
  expect(chat).toContain('class="cue"')
  expect(chat).toContain('syncPillClearance')
  expect(chat).toContain('--thread-top-gap: 3.5rem')
  expect(chat).toContain('BotSettingsSheet')
  expect(thread).toContain('var(--thread-top-gap)')
  expect(thread).toContain('var(--thread-end-gap)')
  expect(pill).toContain('position: absolute')
  expect(pill).toContain('translateX(-50%)')
  expect(pill).toContain('backdrop-filter')
  expect(pill).toContain('padding: 0.18rem 0.7rem')
  expect(pill).not.toContain('--pill-slot')
  expect(pill).not.toContain('width: 100%')
  expect(chat).not.toContain('class="cue-balance"')
  expect(chat).toContain('class="identity-copy"')
  expect(chat).toContain('class="cue-slot"')
  expect(chat).not.toContain('padding: 0.2rem 0.7rem 0.2rem 0.2rem')
  const slot = block('.cue-slot {', '.identity:hover:not(:disabled) .cue-slot')
  expect(slot).toContain('width: 0')
  expect(slot).toContain('opacity: 0')
  const open = block('.identity:hover:not(:disabled) .cue-slot,', '.cue {')
  expect(open).toContain('width: 1.05rem')
})

it('clears pending chips with the draft, before the send POST waits on the reply', () => {
  const deliver = block('async function deliver(', 'async function onBotSaved(')
  const post = deliver.indexOf('await $fetch(`/api/bots/')
  const optimistic = deliver.indexOf('optimistic.value = {')
  const cleared = deliver.indexOf('clearAttachments()')

  expect(post).toBeGreaterThan(-1)
  expect(deliver.indexOf('draft.value = \'\'')).toBeLessThan(post)
  expect(cleared).toBeGreaterThan(optimistic)
  expect(cleared).toBeLessThan(post)
  expect(deliver.lastIndexOf('clearAttachments()')).toBe(cleared)
})
