import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { expect, it } from 'vitest'

const app = join(import.meta.dirname, '../../app')
const chat = readFileSync(join(app, 'pages/bots/[id].vue'), 'utf8')
const room = readFileSync(join(app, 'pages/threads/[id].vue'), 'utf8')
const pillSrc = readFileSync(join(app, 'components/ChatComposerPill.vue'), 'utf8')
const tokens = readFileSync(join(app, 'assets/css/main.css'), 'utf8')

function blockIn(src: string, start: string, end: string): string {
  const from = src.indexOf(start)
  const to = src.indexOf(end, from + start.length)
  expect(from).toBeGreaterThan(-1)
  expect(to).toBeGreaterThan(from)
  return src.slice(from, to)
}

function block(start: string, end: string): string {
  return blockIn(chat, start, end)
}

function pillBlock(start: string, end: string): string {
  return blockIn(pillSrc, start, end)
}

it('overlays a slim composer on one scrolling Chat pane', () => {
  const composer = block('.composer {', '.send-error {')
  const row = pillBlock('.composer-row {', '.composer-row:hover')
  const thread = block('.thread {', '.bubble {')

  expect(composer).toContain('position: absolute')
  expect(composer).toContain('pointer-events: none')
  expect(composer).toContain('env(safe-area-inset-bottom')
  expect(composer).toContain('var(--bg-chat) calc(var(--composer-gap) + 2px)')
  expect(composer).toContain('--composer-gap')
  expect(composer).not.toContain('background: transparent')
  expect(composer).not.toContain('background: var(--composer)')
  const foot = pillBlock('.composer-foot {', '.composer-foot::before')
  const band = pillBlock('.composer-foot::before {', '.composer-row {')
  expect(foot).not.toContain('background:')
  expect(band).toContain('top: 50%')
  expect(band).toContain('bottom: -2px')
  expect(band).toContain('background: var(--bg-chat)')
  expect(band).not.toContain('border-radius')
  expect(row).toContain('background: var(--composer)')
  expect(row).toContain('--composer-pad: 0.3rem;')
  expect(row).toContain('padding: var(--composer-pad);')
  expect(row).toContain('--composer-inner-radius: calc(var(--composer-button) / 2);')
  expect(row).toContain('flex-direction: column')
  expect(row).toContain('border-radius: 9999px')
  expect(row).toContain('pointer-events: auto')
  const tall = pillBlock('.composer-row.multiline {', '.composer-line {')
  expect(tall).toContain('calc(var(--composer-inner-radius) + var(--composer-pad) + var(--composer-rim))')
  const line = pillBlock('.composer-line {', '.composer-row.multiline .composer-line')
  expect(line).toContain('align-items: center')
  const trayAt = pillSrc.indexOf('<slot name="tray" />')
  expect(trayAt).toBeGreaterThan(pillSrc.indexOf('class="composer-row"'))
  expect(trayAt).toBeLessThan(pillSrc.indexOf('class="composer-line"'))
  const pillAt = chat.indexOf('<ChatComposerPill')
  const chipsAt = chat.indexOf('<ChatPendingAttachments')
  expect(chat.indexOf('<template #tray>')).toBeGreaterThan(pillAt)
  expect(chipsAt).toBeGreaterThan(chat.indexOf('<template #tray>'))
  expect(chipsAt).toBeLessThan(chat.indexOf('</ChatComposerPill>'))
  expect(chat).toContain(':tall="pendingAttachments.length > 0"')
  expect(chat).toContain(`:placeholder="pendingAttachments.length > 0
                ? $t('chat.placeholderOrSend')`)
  expect(row).not.toContain('safe-area')
  expect(thread).toContain('var(--composer-clearance)')
  expect(thread).toContain('var(--thread-end-gap)')
  expect(thread).toContain('overflow: auto')
  expect(thread).toContain('overflow-anchor: none')
  expect(chat).toContain('--thread-end-gap: 5rem')
  expect(chat).toContain('el.scrollTop = el.scrollHeight')
  expect(chat).toContain('flush: \'post\', immediate: true')

  const formEnd = chat.indexOf('</form>')
  const jump = chat.indexOf('class="to-latest"')
  expect(formEnd).toBeGreaterThan(-1)
  expect(jump).toBeGreaterThan(formEnd)
  expect(chat).toContain(':aria-label="$t(\'chat.aria.scrollLatest\')"')
  expect(chat).toContain('behavior: reduce ? \'auto\' : \'smooth\'')

  const control = block('.to-latest {', '.to-latest svg')
  expect(control).toContain('left: 50%')
  expect(control).toContain('translateX(-50%)')
  expect(control).toContain('var(--composer-clearance)')
  expect(control).toContain('border-radius: 999px')
  expect(control).toContain('background: var(--composer)')
})

it('overlays a Chat pill and pads the thread above it', () => {
  const thread = block('.thread {', '.bubble {')
  const pill = block('.identity {', '.identity:hover')
  expect(chat).not.toContain('<header')
  expect(chat).toContain('class="cue"')
  expect(chat).toContain('syncPillClearance')
  expect(chat).toContain('--thread-top-gap: 3.5rem')
  expect(chat).toContain('BotSettingsSheet')
  expect(thread).toContain('var(--thread-top-gap)')
  expect(thread).toContain('var(--thread-end-gap)')
  expect(pill).toContain('position: absolute')
  expect(pill).toContain('translateX(-50%)')
  expect(pill).toContain('backdrop-filter')
  expect(pill).toContain('padding: 0.18rem 0.7rem')
  expect(pill).not.toContain('--pill-slot')
  expect(pill).not.toContain('width: 100%')
  expect(chat).not.toContain('class="cue-balance"')
  expect(chat).toContain('class="identity-copy"')
  expect(chat).toContain('class="cue-slot"')
  expect(chat).not.toContain('padding: 0.2rem 0.7rem 0.2rem 0.2rem')
  const slot = block('.cue-slot {', '.identity:hover:not(:disabled) .cue-slot')
  expect(slot).toContain('width: 0')
  expect(slot).toContain('opacity: 0')
  const open = block('.identity:hover:not(:disabled) .cue-slot,', '.cue {')
  expect(open).toContain('width: 1.05rem')
})

it('clears pending chips with the draft, before the send POST waits on the reply', () => {
  const deliver = block('async function deliver(', 'async function onBotSaved(')
  const post = deliver.indexOf('await $fetch(`/api/bots/')
  const optimistic = deliver.indexOf('optimistic.value = {')
  const cleared = deliver.indexOf('clearAttachments()')

  expect(post).toBeGreaterThan(-1)
  expect(deliver.indexOf('draft.value = \'\'')).toBeLessThan(post)
  expect(cleared).toBeGreaterThan(optimistic)
  expect(cleared).toBeLessThan(post)
  expect(deliver.lastIndexOf('clearAttachments()')).toBe(cleared)
})

it('draws Attach as a ghost twin of Send, one circle size on one centerline', () => {
  const circles = pillBlock('.attach,\n.send {', '/* Ghost twin of Send')
  expect(circles).toContain('width: var(--composer-button)')
  expect(circles).toContain('height: var(--composer-button)')
  expect(circles).toContain('border-radius: 999px')
  const ghost = pillBlock('.attach {', '.attach:hover')
  expect(ghost).toContain('background: color-mix(in srgb, var(--text) 9%, transparent)')
  expect(ghost).toContain('box-shadow: inset 0 0 0 1px')
  const field = pillBlock('.composer-line :slotted(textarea) {', '/* With no Attach circle')
  expect(field).toContain('line-height: 1.45rem')
  expect(field).toContain('padding: 0.4rem 0.25rem')
  expect(field).toContain('min-height: 2.25rem')
  expect(field).toContain('field-sizing: content')
  expect(pillSrc).toContain('prefers-reduced-motion: reduce')
})

it('keeps the composer a recessed well with a rim that brightens on hover and focus', () => {
  expect(tokens).toContain('--composer: color-mix(in srgb, var(--surface) 70%, var(--bg-chat));')
  expect(tokens).toContain('--composer-line: color-mix(in srgb, var(--text) 22%, var(--composer));')
  expect(tokens).toContain('--composer-line-strong: color-mix(in srgb, var(--text) 42%, var(--composer));')
  const hover = pillBlock('.composer-row:hover,', '.composer-row.multiline {')
  expect(hover).toContain('.composer-row:focus-within')
  expect(hover).toContain('border-color: var(--composer-line-strong)')
})

it('gives the Room composer the same pill and seal as Bot Chat', () => {
  expect(room).toContain('<ChatComposerPill')
  expect(room).not.toContain('class="composer-row"')
  expect(room).not.toContain('.composer-row {')
  const composer = blockIn(room, '.composer {', '.mention-hint {')
  expect(composer).toContain('var(--bg-chat) calc(var(--composer-gap) + 2px)')
  expect(composer).toContain('pointer-events: none')
  expect(chat).not.toContain('.composer-row {')
  expect(chat).not.toContain('measureComposer')
})

it('attaches Artifacts on a dm, group, or room through the same tray as Bot Chat', () => {
  const tray = readFileSync(join(app, 'components/ChatPendingAttachments.vue'), 'utf8')
  expect(tray).toContain('class="pending-chips"')
  for (const page of [chat, room]) {
    expect(page).toContain('useComposerAttachments()')
    expect(page).toContain('<ChatPendingAttachments')
    expect(page).not.toContain('class="pending-chips"')
    expect(page).toContain(':show-send="Boolean(draft.trim() || canSendAttachments)"')
    expect(page).toContain('@paste="onAttachPaste"')
  }
  const pill = blockIn(room, '<ChatComposerPill', '</ChatComposerPill>')
  expect(pill).toMatch(/\n\s+attach\n/)
  const send = blockIn(room, 'async function send()', '</script>')
  expect(send).toContain('body: { content, artifactIds }')
  expect(send).toContain('(!content && artifactIds.length === 0)')
})

it('opens the @ Bot picker only on a room composer', () => {
  expect(room).toContain('<ChatMentionPicker')
  expect(room).toContain('enabled: computed(() => thread.value?.kind === \'room\')')
  expect(room).toContain('participants.filter((person) => person.kind === \'bot\')')
  expect(chat).not.toContain('ChatMentionPicker')
})

it('asks for an optional line once attachments are pending, with no trailing period', () => {
  const ru = JSON.parse(readFileSync(join(import.meta.dirname, '../../i18n/locales/ru.json'), 'utf8'))
  expect(ru.chat.placeholderOrSend).toBe('Добавьте сообщение или просто отправьте')
})
