import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { BOT_PURPOSE_OPTIONS, BOT_PURPOSE_PROMPT } from '@dostigus/shared'
import { HOST_LOCALE_MESSAGES, tHost } from '@dostigus/ui-kit/locale'
import { expect, it } from 'vitest'

const appRoot = join(import.meta.dirname, '../../app')

function read(rel: string): string {
  return readFileSync(join(appRoot, rel), 'utf8')
}

const leftover = /Day-1|coming soon|MCP token|sealed cookie|Compose env|NUXT_|OPENAI_COMPATIBLE|LLM_API_KEY|stub reply|Host · Cluster/i

it('keeps Create Owner and Sign in free of leftover technical copy', () => {
  const onboarding = read('pages/onboarding.vue')
  const login = read('pages/login.vue')
  expect(onboarding).toContain("$t('auth.onboarding.title')")
  expect(onboarding).toContain("$t('auth.onboarding.hint')")
  expect(onboarding).not.toMatch(leftover)
  expect(login).toContain("$t('auth.login.title')")
  expect(login).toContain("$t('auth.login.hint')")
  expect(login).not.toMatch(leftover)
  expect(login).not.toContain('Password reset')
  expect(tHost('en', 'auth.login.title')).toBe('Welcome back')
  expect(tHost('en', 'auth.onboarding.hint')).toContain('This Host needs one Owner')
})

it('splits Settings into Providers and Other with a left nav', () => {
  const shell = read('pages/settings.vue')
  expect(shell).toContain('<NuxtPage />')
  expect(shell).toContain('\'/settings/providers\'')
  expect(shell).toContain('\'/settings/other\'')
  expect(shell).toContain('settings.nav.providers')
  expect(shell).toContain('settings.nav.other')
  expect(shell).toContain("t('settings.aria')")
  expect(read('pages/settings/index.vue')).toContain('redirect: \'/settings/providers\'')
  const other = read('pages/settings/other.vue')
  expect(other).toContain('settings.other.timezone.title')
  expect(other).toContain('settings.other.allowlist.title')
  expect(other).toContain('settings.other.locale.title')
  expect(other).toContain('/api/settings/timezone')
  expect(other).toContain('/api/settings/http-allowlist')
  expect(read('composables/useHostLocale.ts')).toContain('/api/settings/locale')
  expect(tHost('ru', 'settings.nav.providers')).toBe('Провайдеры')
  expect(tHost('ru', 'settings.nav.other')).toBe('Прочее')
  for (const page of [shell, other]) {
    expect(page).not.toMatch(leftover)
    expect(page).not.toContain('LLM gateway')
  }
})

it('leads Providers with Bots ↔ Providers, key-first OpenRouter, shelf, and health', () => {
  const providers = read('pages/settings/providers.vue')
  const flow = read('components/SettingsLlmFlow.vue')
  const add = read('components/SettingsProviderAdd.vue')
  const shelf = read('components/SettingsOpenRouterShelf.vue')
  const advanced = read('components/SettingsModelCatalog.vue')
  expect(providers).toContain('SettingsLlmFlow')
  expect(providers).toContain('SettingsProviderHealth')
  expect(providers).toContain('SettingsOpenRouterShelf')
  expect(providers).toContain('SettingsModelCatalog')
  expect(providers).toContain('/catalog')
  expect(providers).not.toContain('apiKey: provider.apiKey')
  expect(flow).toContain('settings.providers.flow.botsThink')
  expect(add).toContain('settings.providers.add.connectOpenRouter')
  expect(add).toContain('openai-compatible')
  expect(add).toContain('LLM_PROVIDER_KIND_LABELS')
  expect(shelf).toContain('settings.providers.shelf.routingOff')
  expect(shelf).toContain('OPENROUTER_SHELF_LABELS')
  expect(shelf).toContain('settings.providers.shelf.vision')
  expect(advanced).toContain('settings.providers.catalog.all')
  expect(advanced).toContain('settings.providers.catalog.refresh')
  expect(advanced).toContain('settings.providers.catalog.policy')
  expect(HOST_LOCALE_MESSAGES.ru.settings.providers.details).toBe('Подробнее')
  for (const src of [providers, flow, add, shelf, advanced]) {
    expect(src).not.toMatch(/Day-1|coming soon|Compose env|NUXT_|OPENAI_COMPATIBLE|LLM_API_KEY|stub reply/i)
    expect(src).not.toContain('LLM gateway')
    expect(src).not.toMatch(/['"](?:openai|anthropic|google|meta-llama|qwen|deepseek|x-ai)\/[\w.-]+['"]/)
  }
})

it('keeps Bot list and Chat copy product-facing when no key is set', () => {
  const home = read('pages/index.vue')
  const chat = read('pages/bots/[id].vue')
  const sidebar = read('components/HostSidebar.vue')
  expect(sidebar).toContain('list-empty')
  expect(sidebar).not.toContain('Create a Bot')
  expect(sidebar).not.toContain('HostBotEmpty')
  expect(sidebar).not.toMatch(leftover)
  const empty = read('components/HostBotEmpty.vue')
  expect(home).toContain('HostBotEmpty')
  expect(empty).toContain('name="wave"')
  expect(chat).toContain('authorName')
  expect(chat).not.toContain('class="who"')
  expect(chat).toContain('bot?.name')
  expect(chat).not.toContain('Tell this Bot what it is for')
  expect(chat).toContain('canSendAttachments')
  expect(chat).toContain('artifactIds')
  expect(chat).toContain('onAttachPaste')
  expect(chat).toContain('bindAttachmentWindow')
  expect(chat).toContain('ChatMessageArtifacts')
  expect(chat).toContain('BotPurposeCard')
  const purpose = read('components/BotPurposeCard.vue')
  expect(purpose).toContain('BOT_PURPOSE_OPTIONS')
  expect(purpose).toContain('BOT_PURPOSE_PROMPT')
  expect(BOT_PURPOSE_PROMPT).toBe('What should this Bot be for?')
  expect([...BOT_PURPOSE_OPTIONS]).toEqual(['Personal', 'Work', 'Learning', 'Other'])
  expect(purpose).not.toMatch(leftover)
  expect(purpose).not.toContain('Kinnu')
  const picker = read('components/BotPicker.vue')
  expect(picker).toContain('×')
  expect(picker).not.toContain('background: var(--accent)')
  expect(picker).not.toContain('Kinnu')
  expect(picker).not.toMatch(leftover)
  expect(chat).toContain('ChatActivityRow')
  expect(chat).toContain('threadActivity')
  expect(chat).toContain('v-else-if="botPending"')
  expect(chat).not.toContain('Replying…')
  expect(chat).not.toContain('class="dots"')
  expect(chat).not.toContain('Sending…')
  expect(chat).not.toMatch(/stub|Used Cluster tools|LLM gateway/i)
  expect(picker).toContain('v-if="isOwner"')
  expect(sidebar).toContain('HostPlusMenu')
  expect(sidebar).not.toContain('New thread')
  const plus = read('components/HostPlusMenu.vue')
  expect(plus).toContain("host.plus.findOrCreateBot")
  expect(plus).toContain("host.plus.createGroup")
  expect(plus).not.toContain('Создать группу')
  expect(plus).toContain("host.plus.addMember")
  expect(plus).not.toContain('Kinnu')
  expect(plus).not.toMatch(leftover)
  const composer = read('components/ThreadComposer.vue')
  expect(composer).not.toContain('New thread')
  expect(composer).not.toMatch(leftover)
  expect(read('components/HostMemberAddSheet.vue')).not.toMatch(leftover)
  expect(chat).toContain('v-if="isOwner"')
  expect(read('pages/index.vue')).not.toContain('Kinnu')
})

it('keeps Members copy product-facing', () => {
  const members = read('pages/members.vue')
  expect(members).toContain('members.disable')
  expect(members).toContain('members.inviteByEmail')
  expect(members).toContain('members.copyOnce')
  const invite = read('pages/invite/[token].vue')
  expect(invite).toContain('auth.invite.invalidTitle')
  expect(invite).toContain('auth.invite.joinTitle')
  expect(invite).not.toMatch(/email exists|already registered/i)
  expect(members).not.toMatch(leftover)
  expect(members).not.toContain('Kinnu')
  expect(read('pages/login.vue')).not.toContain('Kinnu')
  expect(read('pages/index.vue')).not.toContain('Kinnu')
  expect(read('components/HostSidebar.vue')).not.toContain('Kinnu')
  expect(read('components/HostUserMenu.vue')).not.toContain('Kinnu')
  expect(read('components/BotSettingsSheet.vue')).not.toContain('Kinnu')
  expect(read('components/BotPicker.vue')).not.toContain('Kinnu')
  expect(read('components/BotPurposeCard.vue')).not.toContain('Kinnu')
  expect(read('pages/bots/[id].vue')).not.toContain('Kinnu')
})
