import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { expect, it } from 'vitest'

const webRoot = join(import.meta.dirname, '../..')

function read(rel: string): string {
  return readFileSync(join(webRoot, rel), 'utf8')
}

it('uses the Kit mark, sticker, Dialog, and Sheet on the Host', () => {
  const mark = read('app/components/HostMark.vue')
  const sidebar = read('app/components/HostSidebar.vue')
  const layout = read('app/layouts/host.vue')
  const picker = read('app/components/BotPicker.vue')
  const purpose = read('app/components/BotPurposeCard.vue')
  const members = read('app/pages/members.vue')
  const settingsPage = read('app/pages/settings.vue')
  const nuxt = read('nuxt.config.ts')

  expect(mark).toContain('GooseLogo')
  expect(mark).not.toContain('🪿')
  expect(sidebar).toContain('No Bots yet')
  expect(sidebar).not.toContain('HostBotEmpty')
  expect(sidebar).not.toContain('name="wave"')
  expect(sidebar).toContain('KitButton')
  expect(sidebar).toContain('placeholder="Search"')
  expect(sidebar).toContain('Collapse sidebar')
  expect(sidebar).toContain('role="separator"')
  expect(sidebar).not.toContain('to="/members"')
  expect(sidebar).not.toContain('to="/settings"')
  const account = read('app/components/HostUserMenu.vue')
  expect(account).toContain('to="/members"')
  expect(account).toContain('to="/settings"')
  expect(account).toContain('HostLogoutButton')
  const settings = read('app/components/BotSettingsSheet.vue')
  expect(settings).toContain('KitSheet')
  expect(settings).toContain('edge="end"')
  expect(settings).toContain('Model tier')
  expect(settings).toContain('Confirm delete')
  expect(settings).toContain('KitBotAvatar')
  expect(settings).toContain('class="tab active"')
  expect(settings).toMatch(/\n\s+Bot\n/)
  expect(settings).toContain('Reset')
  expect(settings).not.toContain('Generate')
  expect(settings).not.toContain('Upload')
  expect(settings).toContain('BOT_AVATAR_SHAPES')
  expect(settings).toContain('BOT_ACCENT_TOKENS')
  expect(settings).toContain('justify-content: center')
  expect(read('app/components/HostBotAvatar.vue')).toContain('KitBotAvatar')
  expect(read('app/components/HostBotAvatar.vue')).toContain('state: \'idle\'')
  const chatPage = read('app/pages/bots/[id].vue')
  expect(chatPage).toContain('markState')
  for (const state of ['think', 'reply', 'celebrate', 'greet', 'listen', 'error', 'sleep']) {
    expect(chatPage).toContain(`'${state}'`)
  }
  expect(chatPage).toContain('@focus="listening = true"')
  expect(chatPage).toContain('@blur="listening = false"')
  expect(settings).toContain('BOT_AVATAR_SHAPE_LABELS')
  expect(settings).toContain('markState')
  expect(read('app/components/HostSidebar.vue')).toContain('avatarShape')
  expect(read('app/pages/bots/[id].vue')).toContain('avatarShape')
  expect(read('app/pages/bots/[id].vue')).toContain('BotSettingsSheet')
  expect(layout).toContain('BotPicker')
  expect(layout).toContain('<slot v-else />')
  expect(layout).not.toContain('BotCreateDialog')
  expect(picker).toContain('Create new Bot')
  expect(picker).toContain('Find or create a Bot')
  expect(picker).toContain('Find a Bot')
  expect(picker).toContain('filterBotsByName')
  expect(picker).toContain('DEFAULT_BOT_NAME')
  expect(picker).toContain('randomBotAppearance')
  expect(picker).toContain('@keydown.enter.prevent')
  expect(picker).toContain('v-if="isOwner"')
  expect(picker).toContain('HostBotAvatar')
  expect(picker).not.toContain('KitDialog')
  expect(picker).not.toContain('aria-modal')
  expect(picker).not.toContain('Close')
  expect(picker).not.toContain('Group')
  expect(picker).not.toContain('⌘')
  expect(picker).not.toContain('metaKey')
  expect(purpose).toContain('BOT_PURPOSE_OPTIONS')
  expect(purpose).toContain('BOT_PURPOSE_PROMPT')
  expect(purpose).toContain('Or type your own')
  expect(chatPage).toContain('BotPurposeCard')
  expect(chatPage).toContain('showsBotPurposeCard')
  expect(members).toContain('KitSheet')
  expect(members).toContain('Add a Member')
  expect(members).toContain('name="peek"')
  expect(members).toContain('layout: \'host\'')
  expect(settingsPage).toContain('layout: \'host\'')
  expect(settingsPage).not.toContain('KitSheet')
  expect(read('app/pages/index.vue')).toContain('layout: \'host\'')
  expect(read('app/pages/bots/[id].vue')).toContain('layout: \'host\'')
  expect(read('app/pages/bots/[id].vue')).toContain('withOptimisticUser')
  expect(read('app/pages/bots/[id].vue')).toContain('botPending')
  expect(nuxt).toContain('gooseFavicon')
  expect(nuxt).toContain('brandDir')
  expect(read('app/app.vue')).toContain('<NuxtLayout>')
})
