import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { expect, it } from 'vitest'

const webRoot = join(import.meta.dirname, '../..')

function read(rel: string): string {
  return readFileSync(join(webRoot, rel), 'utf8')
}

it('uses the Kit mark, sticker, Dialog, and Sheet on the Host', () => {
  const mark = read('app/components/HostMark.vue')
  const sidebar = read('app/components/HostSidebar.vue')
  const layout = read('app/layouts/host.vue')
  const picker = read('app/components/BotPicker.vue')
  const purpose = read('app/components/BotPurposeCard.vue')
  const members = read('app/pages/members.vue')
  const settingsPage = read('app/pages/settings.vue')
  const nuxt = read('nuxt.config.ts')

  expect(mark).toContain('GooseLogo')
  expect(mark).not.toContain('🪿')
  const empty = read('app/components/HostBotEmpty.vue')
  expect(sidebar).toContain('host.sidebar.empty')
  expect(sidebar).toContain('list-empty')
  expect(sidebar).not.toContain('HostBotEmpty')
  expect(sidebar).not.toContain('name="wave"')
  expect(empty).toContain('name="wave"')
  expect(empty).toContain('KitButton')
  expect(empty).toContain('host.empty.createBot')
  expect(read('app/pages/index.vue')).toContain('HostBotEmpty')
  expect(sidebar).toContain('host.nav.search')
  expect(sidebar).toContain('openSearch')
  expect(sidebar).toContain('class="chrome"')
  expect(sidebar.indexOf('class="side-head"')).toBeLessThan(sidebar.indexOf('class="list"'))
  expect(sidebar.indexOf('class="list"')).toBeLessThan(sidebar.indexOf('<HostUserMenu'))
  expect(sidebar).toContain('.rail .side-head')
  expect(sidebar).toContain('order: 2')
  expect(sidebar).toContain('order: 3')
  expect(sidebar).toContain('aspect-ratio: 1')
  expect(sidebar).toContain('width: 2.95rem')
  expect(sidebar).toContain('height: 2.95rem')
  expect(sidebar).not.toContain('KitButton')
  expect(sidebar).not.toContain('placeholder="Search"')
  expect(sidebar).not.toContain('background: var(--accent)')
  expect(sidebar).toContain('host.sidebar.collapse')
  expect(sidebar).toContain('role="separator"')
  expect(sidebar).not.toContain('to="/members"')
  expect(sidebar).not.toContain('to="/settings')
  const account = read('app/components/HostUserMenu.vue')
  expect(account).toContain('to="/members"')
  expect(account).toContain('to="/settings/providers"')
  expect(account).toContain('hideSettings')
  expect(account).toContain('HostLogoutButton')
  const settings = read('app/components/BotSettingsSheet.vue')
  expect(settings).toContain('KitSheet')
  expect(settings).toContain('edge="end"')
  expect(settings).toContain('closet.title')
  expect(settings).toContain('close="icon"')
  expect(settings).toContain('title-align="center"')
  expect(settings).toContain('KitDialog')
  expect(settings).toContain('closet.avatar')
  expect(settings).toContain('closet.save')
  expect(settings).toContain('closet.changeAvatar')
  expect(settings).toContain('class="pencil"')
  expect(settings).toContain('class="hero"')
  expect(settings.match(/@click="openAppearance"/g)).toHaveLength(2)
  expect(settings).not.toContain('class="change"')
  expect(settings).not.toContain('class="mark-hit"')
  expect(settings).not.toContain('>Изменить аватар<')
  expect(settings).toContain('border-radius: 0.7rem')
  expect(settings).toContain('aspect-ratio: 1')
  expect(settings).toContain('--flock-tile: 4.35rem')
  expect(settings).toContain('--flock-width:')
  expect(settings).toContain('--swatch: 1.85rem')
  expect(settings).toContain('right: -0.15rem')
  expect(settings).toContain('bottom: -0.1rem')
  expect(settings).toContain('closet.name')
  expect(settings).toContain('closet.labelOptional')
  expect(settings).toContain('closet.description')
  expect(settings).toContain('closet.schedules')
  expect(settings).toContain('closet.add')
  expect(settings).toContain('<ScheduleSheet')
  expect(settings).toContain('mode="create"')
  expect(settings).toContain('schedule-row')
  expect(settings).not.toContain('Routines')
  expect(settings).not.toContain('Model tier')
  const scheduleSheet = read('app/components/ScheduleSheet.vue')
  expect(scheduleSheet).toContain('schedule.history')
  expect(scheduleSheet).toContain('schedule.noRunsYet')
  expect(scheduleSheet).toContain('schedule.delete')
  expect(scheduleSheet).toContain('schedule.active')
  expect(scheduleSheet).toContain('schedule.instruction')
  expect(scheduleSheet).not.toContain('Routines')
  expect(scheduleSheet).not.toContain('>Cadence<')
  expect(settings).not.toContain('Confirm delete')
  expect(settings).not.toContain('>Delete<')
  expect(settings).toContain('KitBotAvatar')
  expect(settings).toContain('closet.reset')
  expect(settings).not.toContain('Generate')
  expect(settings).not.toContain('Upload')
  expect(settings).toContain('BOT_AVATAR_SHAPES')
  expect(settings).toContain('BOT_ACCENT_TOKENS')
  expect(settings).toContain('justify-content: center')
  expect(read('app/components/HostBotAvatar.vue')).toContain('KitBotAvatar')
  expect(read('app/components/HostBotAvatar.vue')).toContain('state: \'idle\'')
  expect(read('app/components/HostBotAvatar.vue')).toContain('class="live"')
  const chatPage = read('app/pages/bots/[id].vue')
  expect(chatPage).toContain('markState')
  for (const state of ['think', 'reply', 'celebrate', 'greet', 'listen', 'error', 'sleep']) {
    expect(chatPage).toContain(`'${state}'`)
  }
  expect(chatPage).toContain('@focus="listening = true"')
  expect(chatPage).toContain('@blur="listening = false"')
  expect(settings).toContain('closetAvatar.')
  expect(settings).toContain('markState')
  expect(sidebar).toContain(':to="thread.href"')
  expect(sidebar).toContain('kind === \'dm\'')
  expect(sidebar).toContain('kind === \'group\'')
  expect(sidebar).toContain('kind === \'room\'')
  expect(read('app/pages/bots/[id].vue')).toContain('avatarShape')
  expect(read('app/pages/bots/[id].vue')).toContain('BotSettingsSheet')
  expect(layout).toContain('BotPicker')
  expect(layout).toContain('HostSearch')
  expect(layout).toContain('HostMemberAddSheet')
  expect(sidebar).toContain('HostPlusMenu')
  expect(sidebar).not.toContain('New thread')
  expect(sidebar).not.toContain('onNewThread')
  const plus = read('app/components/HostPlusMenu.vue')
  expect(plus).toContain('host.plus.aria')
  expect(plus).toContain('host.plus.createGroup')
  expect(plus).toContain('host.plus.peopleOptionalBot')
  expect(plus).not.toContain('Создать группу')
  expect(plus).not.toContain('Только люди')
  expect(plus).toContain('host.plus.addMember')
  expect(plus).toContain('host.plus.writeDm')
  expect(plus).toContain('host.plus.findOrCreateBot')
  expect(plus).toContain('v-if="isOwner"')
  const composer = read('app/components/ThreadComposer.vue')
  expect(composer).toContain('host.threadCreate.to')
  expect(composer).toContain('host.threadCreate.findPersonOrBot')
  expect(composer).toContain('/api/threads/room-access')
  expect(composer).toContain('host.threadCreate.botOptional')
  expect(composer).toContain('host.threadCreate.botOptional')
  expect(composer).toMatch(/selectedBots\.length === 0/)
  expect(composer).toMatch(/\? 'group'/)
  expect(composer).not.toContain('/grants')
  expect(composer).not.toContain('allCurrentMembers')
  const memberAdd = read('app/components/HostMemberAddSheet.vue')
  expect(memberAdd).toContain('members.addSheet.title')
  expect(memberAdd).toContain('/api/members/invites')
  expect(memberAdd).toContain('/api/members')
  expect(memberAdd).toContain('KitSheet')
  expect(read('app/components/HostBotEmpty.vue')).toContain('host.empty.createGroup')
  expect(read('app/components/HostBotEmpty.vue')).not.toContain('New thread')
  expect(layout).toContain('<slot v-else />')
  expect(layout).not.toContain('BotCreateDialog')
  expect(picker).toContain('host.botPicker.create')
  expect(picker).toContain('host.botPicker.titleOwner')
  expect(picker).toContain('host.botPicker.titleMember')
  expect(picker).toContain('filterBotsByName')
  expect(picker).toContain('DEFAULT_BOT_NAME')
  expect(picker).toContain('randomBotAppearance')
  expect(picker).toContain('@keydown.enter.prevent')
  expect(picker).toContain('v-if="isOwner"')
  expect(picker).toContain('HostBotAvatar')
  expect(picker).not.toContain('KitDialog')
  expect(picker).not.toContain('aria-modal')
  expect(picker).toContain('host.botPicker.back')
  expect(picker).not.toContain('Close')
  expect(picker).not.toContain('background: var(--accent)')
  expect(picker).not.toContain('Group')
  expect(picker).not.toContain('⌘')
  expect(picker).not.toContain('metaKey')
  expect(purpose).toContain('BOT_PURPOSE_OPTIONS')
  expect(purpose).toContain('chat.purpose.prompt')
  expect(purpose).toContain('chat.purpose.own')
  expect(chatPage).toContain('BotPurposeCard')
  expect(chatPage).toContain('showsBotPurposeCard')
  expect(members).toContain('KitSheet')
  expect(members).toContain('members.addSheet.title')
  expect(members).toContain('name="peek"')
  expect(members).toContain('layout: \'host\'')
  expect(settingsPage).toContain('layout: \'settings\'')
  expect(settingsPage).not.toContain('layout: \'host\'')
  expect(settingsPage).not.toContain('KitSheet')
  expect(settingsPage).not.toContain('HostMenuButton')
  expect(settingsPage).not.toContain('HostSidebar')
  const settingsLayout = read('app/layouts/settings.vue')
  expect(settingsLayout).toContain('settings.nav.back')
  expect(settingsLayout).toContain('to="/"')
  expect(settingsLayout).not.toContain('HostSidebar')
  expect(settingsLayout).not.toContain('HostSearch')
  expect(settingsLayout).not.toContain('HostMenuButton')
  expect(settingsLayout).not.toContain('BotPicker')
  expect(read('app/pages/index.vue')).toContain('layout: \'host\'')
  expect(read('app/pages/bots/[id].vue')).toContain('layout: \'host\'')
  expect(read('app/pages/bots/[id].vue')).toContain('withOptimisticUser')
  expect(read('app/pages/bots/[id].vue')).toContain('botPending')
  expect(chatPage).toContain('state="think"')
  expect(chatPage).toContain(':live="botLive"')
  expect(chatPage).toContain('useHostBotActivity')
  expect(chatPage).not.toContain('Replying…')
  expect(nuxt).toContain('gooseFavicon')
  expect(nuxt).toContain('brandDir')
  expect(read('app/app.vue')).toContain('<NuxtLayout>')
})
